## --------------------------------------------------------------------
## BASLOAD ISO CRLF 
## Dad TESTING STUFF
## Dad TESTING STUFF
## Dad TESTING STUFF
## --------------------------------------------------------------------
#CONTROLCODES 1
#SYMFILE "@:TEST1.SYM"
REM #SAVEAS "@:TEST1.PRG"

START:
	POKE $030C,4 : SYS $FF62 : REM --- CHANGE TO THIN PET UPPER/GRAPHICS
	
	
	
	
## ----------------  INCLUDE FILES HERE ----
REM #INCLUDE "SW-MENU.BAS"

