## --------------------------------------------------------------------
## BASLOAD ISO CRLF 
## Andy TESTING STUFF
## --------------------------------------------------------------------
#CONTROLCODES 1
#SYMFILE "@:TEST2.SYM"
REM #SAVEAS "@:TEST2.PRG"

START:
	POKE $030C,4 : SYS $FF62 : REM --- CHANGE TO THIN PET UPPER/GRAPHICS
	
	
	
	
## ----------------  INCLUDE FILES HERE ----
REM #INCLUDE "SW-MENU.BAS"

